Voting38: false
# support for Voting38, https://poggit.pmmp.io/p/Voting38/

Streak:
# The number of streaks a player would recive a rewards
- 100:
 # The command that should be ran as a reward
  commands: "give {player} apple"
 # Message the server about the streaks
  message: "{player} has reached 100 streaks and recived alot of rewards"

# You can add many as you want

